[package]
name = "crossbeam_requests"
description = "Crossbeam channels but with a response"
version = "0.3.0"
license = "MPL-2.0"
authors = ["Johan Bjäreholt <johan@bjareho.lt>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3"
