[package]
name = "mpsc_requests"
description = "mpsc channels but with a response"
version = "0.3.2"
license = "MPL-2.0"
authors = [
    "Johan Bjäreholt <johan@bjareho.lt>",
    "Erik Bjäreholt <erik@bjareholt.com>"
]
edition = "2018"

[dependencies]
crossbeam-channel = "0.4"
